name: Linkspector

on: 
  merge_group:
  push:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6.pre.beta

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
